# Change these first
owner: marcosdid # Your GitHub organization or username, where this repository lives
repo: uptime-teste # The name of this repository
user-agent: marcosdid

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /uptime-teste
  name: ''
  # baseUrl: /your-repo-name
  logoUrl: https://app.kompa.com.br/static/img/logo.png
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: light
  introTitle: "Página com os status dos serviços usados pela Kompa."
  introMessage: Abaixo temos um card com o nome do serviço e seu respectivo status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
